spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=EVRentalSystem;encrypt=false;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true   # in SQL có xuống dòng, dễ đọc

  mail:
    host: smtp.gmail.com
    port: 587
    username: "4aesieunhan.work@gmail.com"
    password: "xjhrbfxyyshneyms"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  messages:
    encoding: UTF-8

server:
  port: 8084
  servlet:
    context-path: /EVRentalSystem
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.hibernate.SQL: DEBUG                 # hiện câu SQL
    org.hibernate.orm.jdbc.bind: TRACE      # hiện giá trị tham số bind
